// <auto-generated />
using System;
using Infraestructure.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infraestructure.Core.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20191106194412_ProcessFiles")]
    partial class ProcessFiles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infraestructure.Entity.Entities.AgentCrossingsEntity", b =>
                {
                    b.Property<int>("AgentCrossingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agent");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<int>("CrossingId");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModificationUser");

                    b.HasKey("AgentCrossingId");

                    b.HasIndex("CrossingId");

                    b.ToTable("AgentCrossings","Crossing");
                });

            modelBuilder.Entity("Infraestructure.Entity.Entities.CrossingsEntity", b =>
                {
                    b.Property<int>("CrossingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Business");

                    b.Property<string>("Company");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<bool?>("Crossed");

                    b.Property<DateTime>("DueDate");

                    b.Property<bool>("Enabled");

                    b.Property<DateTime?>("FinalValidity");

                    b.Property<bool?>("FullPaymentDebts");

                    b.Property<DateTime>("InitialValidity");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModificationUser");

                    b.Property<int>("TypeCrossingId");

                    b.Property<int>("Value");

                    b.HasKey("CrossingId");

                    b.HasIndex("TypeCrossingId");

                    b.ToTable("Crossings","Crossing");
                });

            modelBuilder.Entity("Infraestructure.Entity.Entities.ProcessFile.EquivalenceColumnEntity", b =>
                {
                    b.Property<string>("Origin")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bank");

                    b.Property<string>("ColumnName");

                    b.Property<string>("EquivalenceColumn");

                    b.Property<int>("Position");

                    b.Property<string>("Type");

                    b.HasKey("Origin");

                    b.ToTable("EquivalenceColumn","ProcessFile");
                });

            modelBuilder.Entity("Infraestructure.Entity.Entities.ProcessFile.FileAdministratorEntity", b =>
                {
                    b.Property<int>("BankFileAdminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankCode");

                    b.Property<string>("BusinessCode");

                    b.Property<string>("DetailFileName");

                    b.Property<string>("HeadFileName");

                    b.Property<string>("ReadFolder");

                    b.Property<int>("StartLine");

                    b.Property<bool>("Status");

                    b.HasKey("BankFileAdminId");

                    b.ToTable("FileAdministrator","ProcessFile");
                });

            modelBuilder.Entity("Infraestructure.Entity.Entities.ProcessFile.FileDataDetailEntity", b =>
                {
                    b.Property<int>("BankLoadFileDataDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<int>("BankLoadFileDataId");

                    b.Property<int>("CreditValue");

                    b.Property<int>("DebitValue");

                    b.Property<int>("DetailQuantity");

                    b.Property<string>("TransactionDate");

                    b.Property<string>("TransactionName");

                    b.HasKey("BankLoadFileDataDetailId");

                    b.HasIndex("BankLoadFileDataId");

                    b.ToTable("FileDataDetail","ProcessFile");
                });

            modelBuilder.Entity("Infraestructure.Entity.Entities.ProcessFile.FileDataEntity", b =>
                {
                    b.Property<int>("BankLoadFileDataId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber");

                    b.Property<string>("Bank");

                    b.Property<string>("BusinessCode");

                    b.Property<string>("FileName");

                    b.Property<string>("Origin");

                    b.Property<string>("Type");

                    b.HasKey("BankLoadFileDataId");

                    b.ToTable("FileData","ProcessFile");
                });

            modelBuilder.Entity("Infraestructure.Entity.Entities.TypeCrossingsEntity", b =>
                {
                    b.Property<int>("TypeCrossingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("CreationUser");

                    b.Property<bool>("Enable");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModificationUser");

                    b.Property<string>("Name");

                    b.HasKey("TypeCrossingId");

                    b.ToTable("TypeCrossings","Crossing");
                });

            modelBuilder.Entity("Infraestructure.Entity.Entities.AgentCrossingsEntity", b =>
                {
                    b.HasOne("Infraestructure.Entity.Entities.CrossingsEntity", "CrossingsEntity")
                        .WithMany("AgentCrossingsEntities")
                        .HasForeignKey("CrossingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Infraestructure.Entity.Entities.CrossingsEntity", b =>
                {
                    b.HasOne("Infraestructure.Entity.Entities.TypeCrossingsEntity", "TypeCrossingsEntity")
                        .WithMany("CrossingsEntities")
                        .HasForeignKey("TypeCrossingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Infraestructure.Entity.Entities.ProcessFile.FileDataDetailEntity", b =>
                {
                    b.HasOne("Infraestructure.Entity.Entities.ProcessFile.FileDataEntity", "BankLoadFileDataEntity")
                        .WithMany("BankLoadFileDataDetail")
                        .HasForeignKey("BankLoadFileDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
